# Generated by Django 6.0.3 on 2026-03-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='frame_image_path',
            field=models.CharField(blank=True, default='', help_text='Azure blob path to extracted frame JPEG', max_length=500),
        ),
    ]
