# Generated by Django 6.0.3 on 2026-06-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_add_frame_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='frame_image_path',
            field=models.CharField(blank=True, default='', help_text='S3 key (in processed bucket) of extracted frame JPEG', max_length=500),
        ),
    ]
