# Generated by Django 6.0.3 on 2026-07-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_alter_annotation_frame_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='review_source',
            field=models.CharField(blank=True, choices=[('', 'Not reviewed'), ('human', 'Human'), ('llm', 'LLM')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='annotation',
            name='reviewed',
            field=models.BooleanField(default=False, help_text='A human or the LLM has vetted these boxes.'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
