# Generated by Django 6.0.3 on 2026-07-08 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_annotation_review_source_annotation_reviewed_and_more'),
        ('videos', '0007_pendingdevicedeletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreAnnotationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('labeler', models.CharField(default='yolo', max_length=20)),
                ('custom_model_key', models.CharField(blank=True, default='', max_length=500)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('output_uri', models.CharField(blank=True, default='', max_length=700)),
                ('failure_uri', models.CharField(blank=True, default='', max_length=700)),
                ('frames_written', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preannotation_tasks', to='annotations.annotationproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preannotation_tasks', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preannotation_tasks', to='videos.video')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
