# Generated by Django 6.0.3 on 2026-07-22 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0006_alter_preannotationtask_status'),
        ('videos', '0007_pendingdevicedeletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='sampled_only',
            field=models.BooleanField(default=False, help_text='This row is a sampled frame nobody has annotated yet — it exists so the editor can navigate to the frame. Distinct from a frame a human deliberately marked empty, which IS a valid negative example; training excludes these but keeps those.'),
        ),
        migrations.CreateModel(
            name='FrameSamplingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('frames_written', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_sampling_tasks', to='annotations.annotationproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_sampling_tasks', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_sampling_tasks', to='videos.video')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
