# Generated by Django 6.0.3 on 2026-09-10 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0008_clipassignment_projectshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationproject',
            name='copied_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='annotations.annotationproject'),
        ),
        migrations.AddField(
            model_name='annotationproject',
            name='copied_from_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='annotationproject',
            name='publish_metadata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotationproject',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotationproject',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private — only people you share it with'), ('public', 'Public — anyone can view and take a copy')], default='private', max_length=10),
        ),
    ]
