# Generated by Django 6.1.1 on 2026-09-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0009_annotationproject_copied_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='framesamplingtask',
            name='motion',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
