# Generated by Django 6.1.1 on 2026-09-24 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0010_framesamplingtask_motion'),
        ('videos', '0009_video_height_video_width'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='framesamplingtask',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SamplingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('claimed', 'Claimed'), ('invoked', 'Invoked'), ('collecting', 'Collecting'), ('collected', 'Collected'), ('failed', 'Failed')], default='claimed', max_length=20)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('result_key', models.CharField(blank=True, default='', max_length=300)),
                ('output_uri', models.CharField(blank=True, default='', max_length=700)),
                ('failure_uri', models.CharField(blank=True, default='', max_length=700)),
                ('error', models.TextField(blank=True, default='')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('invoked_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['claimed_at'],
                'indexes': [models.Index(fields=['status', 'claimed_at'], name='annotations_status_07fb84_idx')],
            },
        ),
        migrations.AddField(
            model_name='framesamplingtask',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='annotations.samplingbatch'),
        ),
        migrations.AddIndex(
            model_name='framesamplingtask',
            index=models.Index(fields=['status', 'created_at'], name='annotations_status_04f88b_idx'),
        ),
    ]
