# Generated by Django 6.1.1 on 2026-09-25 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clips_to_frames(apps, schema_editor):
    """Each clip assignment becomes an assignment of that clip's unreviewed
    frames to the same person. Reviewed frames are done; nobody holds them."""
    ClipAssignment = apps.get_model("annotations", "ClipAssignment")
    Annotation = apps.get_model("annotations", "Annotation")
    for a in ClipAssignment.objects.all().iterator():
        Annotation.objects.filter(
            project_id=a.project_id, video_id=a.video_id, reviewed=False,
            assigned_to__isnull=True,
        ).update(assigned_to_id=a.user_id, assigned_by_id=a.assigned_by_id,
                 assigned_at=a.assigned_at)


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0011_sampling_batch'),
        ('videos', '0009_video_height_video_width'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_frames', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['project', 'reviewed', 'assigned_to'], name='ann_review_queue'),
        ),
        migrations.RunPython(clips_to_frames, migrations.RunPython.noop),
    ]
