# Generated by Django 6.1.1 on 2026-09-25 16:21

from django.db import migrations, models


def annotators_to_reviewers(apps, schema_editor):
    """SAM 3 labels; people review. Every annotator is now a reviewer."""
    apps.get_model("annotations", "ProjectShare").objects.filter(
        role="annotator").update(role="reviewer")


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0012_frame_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectshare',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer — see frames and labels'), ('reviewer', "Reviewer — check and fix the AI's boxes"), ('manager', 'Manager — add clips, run sampling, assign frames')], default='reviewer', max_length=16),
        ),
        migrations.RunPython(annotators_to_reviewers, migrations.RunPython.noop),
    ]
