# Generated by Django 6.0.3 on 2026-03-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='credit_reset_date',
            field=models.DateField(blank=True, help_text='Next monthly reset date', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_concurrent_jobs',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monthly_credit_cents',
            field=models.IntegerField(default=3000, help_text='Monthly credit limit in cents'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_gpu_seconds',
            field=models.FloatField(default=0, help_text='Lifetime GPU seconds consumed'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_jobs_submitted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='used_credit_cents',
            field=models.IntegerField(default=0, help_text='Credits used this month in cents'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
