# Generated by Django 6.0.3 on 2026-03-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_credit_reset_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='monthly_credit_cents',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='used_credit_cents',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monthly_credits',
            field=models.IntegerField(default=3000, help_text='Monthly credit limit'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='used_credits',
            field=models.IntegerField(default=0, help_text='Credits used this month'),
        ),
    ]
