# Generated by Django 6.0.3 on 2026-03-20 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_monthly_credit_cents_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('coupon_type', models.CharField(choices=[('credits', 'Credits'), ('tier_upgrade', 'Tier Upgrade')], max_length=20)),
                ('credits_amount', models.IntegerField(default=0, help_text='Bonus credits to add')),
                ('upgrade_tier', models.CharField(blank=True, choices=[('free', 'Free'), ('standard', 'Standard'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='', help_text='Tier to upgrade user to', max_length=20)),
                ('upgrade_duration_days', models.IntegerField(default=30, help_text='How long tier upgrade lasts')),
                ('max_redemptions', models.IntegerField(default=0, help_text='0 = unlimited')),
                ('times_redeemed', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('credits_added', models.IntegerField(default=0)),
                ('previous_tier', models.CharField(blank=True, max_length=20)),
                ('new_tier', models.CharField(blank=True, max_length=20)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='accounts.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('coupon', 'user')},
            },
        ),
    ]
