# Generated by Django 6.0.3 on 2026-03-22 06:22

from django.db import migrations


def create_enterprise_coupon(apps, schema_editor):
    Coupon = apps.get_model("accounts", "Coupon")
    Coupon.objects.get_or_create(
        code="BEEMONITOR-ENTERPRISE",
        defaults={
            "coupon_type": "tier_upgrade",
            "credits_amount": 0,
            "upgrade_tier": "enterprise",
            "upgrade_duration_days": 365,
            "max_redemptions": 1,
            "is_active": True,
        },
    )


def remove_enterprise_coupon(apps, schema_editor):
    Coupon = apps.get_model("accounts", "Coupon")
    Coupon.objects.filter(code="BEEMONITOR-ENTERPRISE").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_coupon_system'),
    ]

    operations = [
        migrations.RunPython(create_enterprise_coupon, remove_enterprise_coupon),
    ]
