# Generated by Django 6.0.3 on 2026-05-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_create_enterprise_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_support',
            field=models.BooleanField(default=False, help_text='Allow read-only cross-tenant access (analytics, debugging). Writes still owner-scoped.'),
        ),
    ]
