config:
  azure-native:location: eastus
  beemonitor-infra:environment: dev
  beemonitor-infra:appServiceSku: B1
  beemonitor-infra:postgresSkuName: Standard_B1ms
  beemonitor-infra:postgresTier: Burstable
