# Generated by Django 6.0.3 on 2026-03-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='recorded_at',
            field=models.DateTimeField(blank=True, help_text='When the video was recorded', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='site_name',
            field=models.CharField(blank=True, help_text='Field site name', max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
