# Generated by Django 6.0.3 on 2026-05-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_day_video_hour_video_month_video_recorded_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='storage_key',
            new_name='storage_key',
        ),
    ]
