# Generated by Django 6.0.3 on 2026-06-04 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_deviceheartbeat'),
        ('videos', '0003_rename_azure_blob_path_video_storage_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='devices.device'),
        ),
    ]
