# Generated by Django 6.0.3 on 2026-06-10 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_deviceshare'),
        ('videos', '0006_video_device_delete_requested_device_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDeviceDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_deletions', to='devices.device')),
            ],
            options={
                'unique_together': {('device', 'video_id')},
            },
        ),
    ]
