# Generated by Django 6.0.3 on 2026-09-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_pendingdevicedeletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_key',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
