# Generated by Django 6.0.3 on 2026-09-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_video_thumbnail_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
