# Generated by Django 6.1.1 on 2026-09-26 23:15

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0037_motion_burst_and_device_delete'),
        ('sources', '0002_alter_datasource_source_type'),
        ('videos', '0009_video_height_video_width'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'base_manager_name': 'everything', 'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelManagers(
            name='video',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='pendingdevicedeletion',
            name='is_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='kind',
            field=models.CharField(choices=[('video', 'Video'), ('photo', 'Photo')], default='video', max_length=8),
        ),
        migrations.AddField(
            model_name='video',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='videos.video'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['device', 'kind', 'recorded_at'], name='video_device_kind_rec'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['kind', 'recorded_at'], name='video_kind_rec'),
        ),
    ]
