# Generated by Django 6.0.3 on 2026-06-04 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('image_storage_key', models.CharField(blank=True, max_length=500)),
                ('storage_pct', models.FloatField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', '-created_at'], name='devices_dev_device__f21342_idx')],
            },
        ),
    ]
