# Generated by Django 6.0.3 on 2026-06-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_command_params_device_last_fix_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceheartbeat',
            name='snippets_last_period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
