# Generated by Django 6.0.3 on 2026-06-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_deviceheartbeat_snippets_last_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='stream_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='stream_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
