# Generated by Django 6.0.3 on 2026-06-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_stream_expires_at_device_stream_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='last_fix_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='last_lat',
        ),
        migrations.RemoveField(
            model_name='device',
            name='last_lon',
        ),
        migrations.AddField(
            model_name='device',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, help_text="Optional label, e.g. 'north hedgerow'.", max_length=200),
        ),
    ]
