# Generated by Django 6.0.3 on 2026-06-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_deviceshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='telemetry_interval_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
