# Generated by Django 6.0.3 on 2026-06-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_device_telemetry_interval_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='tz_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='device',
            name='tz_offset_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
