# Generated by Django 6.0.3 on 2026-06-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_device_tz_name_device_tz_offset_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='motion_max_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='motion_min_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='motion_min_blobs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='motion_var_threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
