# Generated by Django 6.0.3 on 2026-06-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_device_motion_max_area_device_motion_min_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='first_image_requested',
            field=models.BooleanField(default=False),
        ),
    ]
