# Generated by Django 6.0.3 on 2026-06-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_device_first_image_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='nest_layout',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='device',
            name='roi_override',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
