# Generated by Django 6.0.3 on 2026-06-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_device_nest_layout_device_roi_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='display_tz',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
