# Generated by Django 6.0.3 on 2026-06-12 15:12

import apps.devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_device_hw_id_enrollmenttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='wake_schedule',
            field=models.JSONField(blank=True, default=apps.devices.models.default_wake_schedule),
        ),
    ]
