# Generated by Django 6.0.3 on 2026-06-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_device_wake_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='wake_schedule_apply',
            field=models.BooleanField(default=False),
        ),
    ]
