# Generated by Django 6.0.3 on 2026-06-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_device_wake_schedule_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='frame_daily_cap',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
