# Generated by Django 6.0.3 on 2026-06-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_frame_daily_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='bee_confirm_mode',
            field=models.CharField(blank=True, choices=[('', 'Device default'), ('off', 'Off'), ('tag', 'Tag (observe only)'), ('gate', 'Gate (filter)')], default='', max_length=8),
        ),
    ]
