# Generated by Django 6.0.3 on 2026-06-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_bee_confirm_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='bee_confirm_mode',
            field=models.CharField(blank=True, choices=[('', "Default (unit's env setting)"), ('off', 'Off — track all activity'), ('tag', 'Observe — label only'), ('gate', 'Filter — drop unconfirmed')], default='', max_length=8),
        ),
    ]
