# Generated by Django 6.0.3 on 2026-06-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0019_alter_device_bee_confirm_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='send_activity_crops',
            field=models.BooleanField(default=True),
        ),
    ]
