# Generated by Django 6.0.3 on 2026-06-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_activity_crops_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='update_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='update_target',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
