# Generated by Django 6.0.3 on 2026-07-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0022_device_update_requested_at_device_update_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='video_upload_mode',
            field=models.CharField(choices=[('manual', "Manual — hold videos until 'Upload now'"), ('auto', 'Auto — upload whenever WiFi is connected')], default='manual', max_length=8),
        ),
    ]
