# Generated by Django 6.0.3 on 2026-07-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0023_device_video_upload_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='record_mode',
            field=models.CharField(choices=[('motion', 'Motion-triggered (default)'), ('continuous', 'Continuous — save in 10-minute clips')], default='motion', max_length=12),
        ),
        migrations.AddField(
            model_name='device',
            name='record_window',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
