# Generated by Django 6.0.3 on 2026-07-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0024_device_record_mode_device_record_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='record_max_segment',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='device',
            name='record_post_roll',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
