# Generated by Django 6.0.3 on 2026-07-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0025_device_record_max_segment_device_record_post_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='record_mode',
            field=models.CharField(choices=[('off', 'Off — recording disabled'), ('motion', 'Motion-triggered (default)'), ('continuous', 'Continuous — save in 10-minute clips')], default='motion', max_length=12),
        ),
    ]
