# Generated by Django 6.0.3 on 2026-07-22 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0026_alter_device_record_mode'),
        ('pipelines', '0004_pipelinerun_batch_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePipelineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('cadence', models.CharField(choices=[('hourly', 'Every hour'), ('every_6h', 'Every 6 hours'), ('daily', 'Once a day')], default='daily', max_length=16)),
                ('at_hour', models.IntegerField(blank=True, help_text='Hour of day (device-local) for the daily cadence; null = any hour.', null=True)),
                ('lookback_hours', models.IntegerField(default=1, help_text='Overlap added to the back of the window so a clip that lands late (or a missed tick) still gets picked up. Re-runs are cheap: an identical GPU step reuses its StepResult cache.')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_batch_id', models.UUIDField(blank=True, null=True)),
                ('last_launched_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_schedules', to='devices.device')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_schedules', to='pipelines.pipeline')),
                ('user', models.ForeignKey(help_text='Whose runs + credits these launches are billed to.', on_delete=django.db.models.deletion.CASCADE, related_name='device_pipeline_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('device', 'pipeline'), name='uniq_device_pipeline_schedule')],
            },
        ),
    ]
