# Generated by Django 6.0.3 on 2026-09-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0028_device_roi_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='rotate_180',
            field=models.BooleanField(default=False, help_text="Display this device's videos rotated 180°. For footage recorded before the camera's flip settings were corrected."),
        ),
    ]
