# Generated by Django 6.1.1 on 2026-09-23 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0032_remove_fixed_device_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHealthSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.DateTimeField()),
                ('storage_pct', models.FloatField(blank=True, null=True)),
                ('cpu_temp_c', models.FloatField(blank=True, null=True)),
                ('uptime_seconds', models.IntegerField(blank=True, null=True)),
                ('pending_uploads', models.IntegerField(blank=True, null=True)),
                ('clips_this_hour', models.IntegerField(blank=True, null=True)),
                ('services_healthy', models.IntegerField(blank=True, null=True)),
                ('services_total', models.IntegerField(blank=True, null=True)),
                ('transport', models.CharField(blank=True, default='', max_length=16)),
                ('battery_voltage', models.FloatField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_samples', to='devices.device')),
            ],
            options={
                'ordering': ['minute'],
                'constraints': [models.UniqueConstraint(fields=('device', 'minute'), name='uniq_health_device_minute')],
            },
        ),
    ]
