# Generated by Django 6.1.1 on 2026-09-23 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0033_device_health_sample'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLayoutVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('roi_override', models.JSONField(blank=True, null=True)),
                ('roi_polygon', models.JSONField(blank=True, null=True)),
                ('nest_layout', models.JSONField(blank=True, default=list)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_versions', to='devices.device')),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-number'],
                'indexes': [models.Index(fields=['device', 'applied_at'], name='devices_dev_device__f5046d_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'number'), name='uniq_layout_device_number')],
            },
        ),
    ]
