# Generated by Django 6.1.1 on 2026-09-26 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0035_seed_layout_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='stills_interval_min',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Off'), (15, 'Every 15 min'), (30, 'Every 30 min'), (60, 'Every hour')], default=0),
        ),
        migrations.CreateModel(
            name='DeviceStill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField()),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('thumb_key', models.CharField(blank=True, default='', max_length=500)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('sensor_mode', models.CharField(blank=True, default='', max_length=8)),
                ('lens_position', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='schedule', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stills', to='devices.device')),
            ],
            options={
                'ordering': ['-taken_at'],
                'indexes': [models.Index(fields=['device', 'taken_at'], name='devices_dev_device__cc1afe_idx')],
            },
        ),
    ]
