# Generated by Django 6.1.1 on 2026-09-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0036_device_stills'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='motion_burst_stills',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devicestill',
            name='burst_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='devicestill',
            name='burst_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicestill',
            name='device_delete_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicestill',
            name='device_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
