# Generated by Django 6.0.3 on 2026-07-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='graph',
            field=models.JSONField(blank=True, default=dict, help_text='Raw Drawflow node-graph export (canvas layout). Derived into `steps` on save; empty for pipelines built before the canvas.'),
        ),
    ]
