# Generated by Django 6.0.3 on 2026-07-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0003_stepresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
