# Generated by Django 6.0.3 on 2026-09-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0004_pipelinerun_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='fresh',
            field=models.BooleanField(default=False),
        ),
    ]
