# Generated by Django 6.0.3 on 2026-03-17 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_job_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('ingesting', 'Ingesting'), ('processing', 'Processing'), ('post_processing', 'Post-Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('progress_pct', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('compute_cost_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='videos.video')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_csv_path', models.CharField(blank=True, max_length=500)),
                ('tracking_csv_path', models.CharField(blank=True, max_length=500)),
                ('annotated_video_path', models.CharField(blank=True, max_length=500)),
                ('total_events', models.IntegerField(default=0)),
                ('entry_count', models.IntegerField(default=0)),
                ('exit_count', models.IntegerField(default=0)),
                ('unique_tracks', models.IntegerField(default=0)),
                ('nest_count', models.IntegerField(default=0)),
                ('summary_stats', models.JSONField(blank=True, default=dict)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analysis.job')),
            ],
        ),
    ]
