# Generated by Django 6.0.3 on 2026-03-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='modal_call_id',
            field=models.CharField(blank=True, help_text='Modal FunctionCall ID for async polling', max_length=200),
        ),
    ]
