# Generated by Django 6.0.3 on 2026-03-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_job_modal_call_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='config_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA256 hash for deduplication', max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='execution_seconds',
            field=models.FloatField(blank=True, help_text='Actual GPU seconds consumed', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='gpu_tier',
            field=models.CharField(choices=[('T4', 'T4 (Budget)'), ('L4', 'L4 (Standard)'), ('A10G', 'A10G (Fast)'), ('L40S', 'L40S (Faster)'), ('A100', 'A100 (Fastest)')], default='A10G', max_length=10),
        ),
    ]
