# Generated by Django 6.0.3 on 2026-03-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_job_config_hash_job_execution_seconds_job_gpu_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobresult',
            name='avg_trip_duration_sec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobresult',
            name='foraging_trip_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobresult',
            name='foraging_trips_csv_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
