# Generated by Django 6.0.3 on 2026-03-23 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_foraging_trip_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyForagingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('total_trips', models.IntegerField(default=0)),
                ('cross_video_trips', models.IntegerField(default=0)),
                ('avg_duration_sec', models.FloatField(default=0)),
                ('median_duration_sec', models.FloatField(default=0)),
                ('trips_per_nest', models.JSONField(blank=True, default=dict)),
                ('trips_csv_path', models.CharField(blank=True, max_length=500)),
                ('video_count', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_foraging', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'site_name', 'date')},
            },
        ),
    ]
