# Generated by Django 6.0.3 on 2026-03-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_daily_foraging_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobresult',
            name='interaction_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobresult',
            name='interactions_csv_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
