# Generated by Django 6.0.3 on 2026-06-06 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _clear_summaries(apps, schema_editor):
    """Wipe the derived foraging-summary cache so it rebuilds device-keyed.

    Old rows have device=NULL; without clearing them the entrypoint's
    compute_daily_trips would add device-keyed rows alongside the legacy ones
    and double-count. These rows are regenerated automatically by
    compute_daily_trips (runs on container start).
    """
    apps.get_model("analysis", "DailyForagingSummary").objects.all().delete()


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_interaction_fields'),
        ('devices', '0006_remove_device_last_fix_at_remove_device_last_lat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyforagingsummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyforagingsummary',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_foraging', to='devices.device'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyforagingsummary',
            unique_together={('user', 'site_name', 'device', 'date')},
        ),
        migrations.RunPython(_clear_summaries, _noop),
    ]
