# Generated by Django 6.0.3 on 2026-07-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_alter_dailyforagingsummary_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobresult',
            name='species_csv_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
