# Generated by Django 6.0.3 on 2026-07-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_jobresult_species_csv_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobresult',
            name='species_csv_path',
        ),
        migrations.AddField(
            model_name='jobresult',
            name='crops_csv_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
