# Generated by Django 6.0.3 on 2026-07-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_remove_jobresult_species_csv_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyforagingsummary',
            name='stale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyforagingsummary',
            name='stale_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyforagingsummary',
            name='trips',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
