# Generated by Django 6.0.3 on 2026-07-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_dailyforagingsummary_stale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobresult',
            name='detections_csv_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
