# Generated by Django 6.0.3 on 2026-09-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_jobresult_detections_csv_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='gpu_seconds',
            field=models.FloatField(blank=True, help_text='GPU inference seconds (subset of execution_seconds)', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stage_seconds',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='job',
            name='execution_seconds',
            field=models.FloatField(blank=True, help_text='Handler wall seconds — what is billed', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='gpu_tier',
            field=models.CharField(choices=[('T4', 'T4 (Budget)'), ('L4', 'L4 (Standard)'), ('A10G', 'A10G (Fast)'), ('L40S', 'L40S (Faster)'), ('A100', 'A100 (Fastest)')], default='T4', max_length=10),
        ),
    ]
