# Generated by Django 6.0.3 on 2026-05-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('aws_s3', 'AWS S3'), ('gcs', 'Google Cloud Storage'), ('google_drive', 'Google Drive')], max_length=20),
        ),
    ]
