# Generated by Django 6.0.3 on 2026-06-12 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0014_device_hw_id_enrollmenttoken'),
        ('videos', '0007_pendingdevicedeletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_uid', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('peak_motion', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending analysis'), ('analyzing', 'Analyzing'), ('analyzed', 'Analyzed'), ('no_detection', 'No organism detected'), ('failed', 'Analysis failed')], default='pending', max_length=16)),
                ('best_confidence', models.FloatField(blank=True, null=True)),
                ('individual_count', models.PositiveIntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='devices.device')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='videos.video')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('crop', 'Mover crop'), ('wide', 'Wide context')], default='crop', max_length=8)),
                ('storage_key', models.CharField(help_text='S3 key in the raw-videos bucket.', max_length=500)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('motion_score', models.FloatField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='monitor.activity')),
            ],
            options={
                'ordering': ['captured_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('kingdom', 'Kingdom'), ('phylum', 'Phylum'), ('class', 'Class'), ('order', 'Order'), ('family', 'Family'), ('genus', 'Genus'), ('species', 'Species')], max_length=20)),
                ('name', models.CharField(help_text='Scientific name at this rank.', max_length=200)),
                ('common_name', models.CharField(blank=True, default='', max_length=200)),
                ('gbif_id', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='monitor.taxon')),
            ],
            options={
                'ordering': ['rank', 'name'],
                'unique_together': {('rank', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('individual_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('auto', 'Auto (pipeline)'), ('agent_reviewed', 'Agent-reviewed'), ('human_confirmed', 'Human-confirmed')], default='auto', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='monitor.activity')),
                ('representative_frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitor.activityframe')),
                ('taxon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='monitor.taxon')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('bioclip', 'BioCLIP (insect)'), ('plantnet', 'Pl@ntNet (plant)')], default='bioclip', max_length=16)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict, help_text='Full ranked model output.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='monitor.activityframe')),
                ('taxon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='monitor.taxon')),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='best_taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitor.taxon'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['device', '-started_at'], name='monitor_act_device__105905_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('device', 'activity_uid')},
        ),
    ]
