# Generated by Django 6.0.3 on 2026-06-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='detection',
            constraint=models.UniqueConstraint(fields=('frame', 'model'), name='uniq_detection_per_frame_model'),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(fields=('activity',), name='uniq_observation_per_activity'),
        ),
    ]
