# Generated by Django 6.0.3 on 2026-06-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_detection_uniq_detection_per_frame_model_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='observation',
            name='uniq_observation_per_activity',
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(fields=('activity', 'taxon'), name='uniq_observation_per_activity_taxon'),
        ),
    ]
