# Generated by Django 6.0.3 on 2026-06-12 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_device_hw_id_enrollmenttoken'),
        ('monitor', '0004_agentconversation_agentmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The UTC day summarized.')),
                ('summary', models.TextField()),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digests', to='devices.device')),
            ],
            options={
                'ordering': ['-date', 'device__name'],
                'constraints': [models.UniqueConstraint(fields=('device', 'date'), name='uniq_digest_per_device_day')],
            },
        ),
    ]
