# Generated by Django 6.0.3 on 2026-06-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_dailydigest'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityframe',
            name='frame_uid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
    ]
