# Generated by Django 6.0.3 on 2026-03-19 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('base_model', models.CharField(choices=[('yolov8n', 'YOLOv8n (Nano)'), ('yolov8s', 'YOLOv8s (Small)'), ('yolov8m', 'YOLOv8m (Medium)'), ('yolov11n', 'YOLOv11n (Nano)'), ('yolov11s', 'YOLOv11s (Small)')], max_length=50)),
                ('epochs', models.IntegerField(default=50)),
                ('image_size', models.IntegerField(default=640)),
                ('batch_size', models.IntegerField(default=16)),
                ('gpu_tier', models.CharField(choices=[('T4', 'T4 (Budget)'), ('L4', 'L4 (Standard)'), ('A10G', 'A10G (Fast)'), ('L40S', 'L40S (Faster)'), ('A100', 'A100 (Fastest)')], default='A10G', max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('preparing', 'Preparing'), ('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('modal_call_id', models.CharField(blank=True, max_length=200)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Training metrics: mAP50, mAP50-95, precision, recall, best_epoch')),
                ('execution_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='annotations.annotationproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('nest_detection', 'Nest Detection'), ('bee_tracking', 'Bee Tracking'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('base_model', models.CharField(max_length=50)),
                ('azure_model_path', models.CharField(blank=True, max_length=500)),
                ('classes', models.JSONField(default=list)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_models', to=settings.AUTH_USER_MODEL)),
                ('training_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_model', to='training.trainingjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
