# Generated by Django 6.0.3 on 2026-05-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custommodel',
            old_name='storage_key',
            new_name='storage_key',
        ),
    ]
