# Generated by Django 6.0.3 on 2026-06-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_rename_azure_model_path_custommodel_storage_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommodel',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('training', 'Training'), ('failed', 'Failed')], default='ready', max_length=20),
        ),
    ]
