# Generated by Django 6.0.3 on 2026-07-03 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_custommodel_status'),
        ('videos', '0007_pendingdevicedeletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriftReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='default', max_length=100)),
                ('centroid', models.JSONField(default=list)),
                ('ref_mean', models.FloatField(default=0.0)),
                ('ref_std', models.FloatField(default=0.0)),
                ('dim', models.IntegerField(default=0)),
                ('n_frames', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_references', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'scope')},
            },
        ),
        migrations.CreateModel(
            name='DriftCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drift_score', models.FloatField(default=0.0)),
                ('z_score', models.FloatField(default=0.0)),
                ('is_drifted', models.BooleanField(default=False)),
                ('n_frames', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_checks', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_checks', to='videos.video')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='training.driftreference')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
