# Generated by Django 6.0.3 on 2026-07-03 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_alter_annotation_frame_image_path'),
        ('training', '0004_driftreference_driftcheck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='default', max_length=100)),
                ('status', models.CharField(choices=[('relabeling', 'Relabeling (SAM 3)'), ('training', 'Training'), ('evaluating', 'Evaluating'), ('awaiting_approval', 'Awaiting approval'), ('promoted', 'Promoted'), ('held', 'Held (below bar)'), ('failed', 'Failed')], default='relabeling', max_length=24)),
                ('min_map50', models.FloatField(default=0.5)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adaptation_runs', to='training.custommodel')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adaptation_runs', to='annotations.annotationproject')),
                ('training_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adaptation_runs', to='training.trainingjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
