# Generated by Django 6.0.3 on 2026-07-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_adaptationrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjob',
            name='frame_filter',
            field=models.CharField(choices=[('all', 'All annotated frames'), ('reviewed', 'Reviewed frames only (human + LLM)'), ('human', 'Human-reviewed frames only')], default='all', help_text="Which of the project's annotated frames go into the dataset.", max_length=10),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='init_from_label',
            field=models.CharField(blank=True, default='', help_text='Human-readable name of the fine-tune source model.', max_length=200),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='init_weights_key',
            field=models.CharField(blank=True, default='', help_text='S3 key (models bucket) of .pt weights to fine-tune from; empty = train from the pretrained base architecture.', max_length=500),
        ),
    ]
