# Generated by Django 6.0.3 on 2026-07-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_trainingjob_frame_filter_trainingjob_init_from_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjob',
            name='val_percent',
            field=models.IntegerField(default=20, help_text='Percent of frames held out for validation (the metrics set).'),
        ),
    ]
