# Generated by Django 6.0.3 on 2026-07-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_fix_finetuned_base_model_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='driftreference',
            name='auto_adapt',
            field=models.BooleanField(default=False),
        ),
    ]
