# Generated by Django 6.0.3 on 2026-07-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_driftreference_auto_adapt'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjob',
            name='class_subset',
            field=models.JSONField(blank=True, default=list, help_text="Subset of the project's classes to train on. Empty = all classes."),
        ),
    ]
