# Generated by Django 6.0.3 on 2026-07-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_trainingjob_class_subset'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjob',
            name='frames_with_class',
            field=models.BooleanField(default=False, help_text='Only include frames that contain at least one box of the selected class(es) — skip frames without any.'),
        ),
    ]
