# Generated by Django 6.0.3 on 2026-09-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_trainingjob_frames_with_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommodel',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custommodel',
            name='trained_on',
            field=models.JSONField(blank=True, default=dict, help_text='Project name, frame/box counts, hotels and hours at the time of training. A snapshot, never a live lookup.'),
        ),
        migrations.AddField(
            model_name='custommodel',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public — anyone can use it in a pipeline')], default='private', max_length=10),
        ),
    ]
