# Generated by Django 6.0.3 on 2026-10-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_custommodel_published_at_custommodel_trained_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingjob',
            name='base_model',
            field=models.CharField(choices=[('yolov8n', 'YOLOv8n (Nano)'), ('yolov8s', 'YOLOv8s (Small)'), ('yolov8m', 'YOLOv8m (Medium)'), ('yolov11n', 'YOLOv11n (Nano)'), ('yolov11s', 'YOLOv11s (Small)'), ('yolo26n', 'YOLO26n (Nano)'), ('yolo26s', 'YOLO26s (Small)'), ('yolo26m', 'YOLO26m (Medium)')], max_length=50),
        ),
    ]
